server:
  port: 10010

spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: zhongliang-yuangong
          uri: lb://zhongliang-yuangong
          predicates:
            - Path=/yuangong/**
        - id: xian-huiyuan
          uri: lb://xian-huiyuan
          predicates:
            - Path=/huiyuan/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:9090/eureka
