server:
  port: 9090

spring:
  application:
    name: eureka-server

eureka:
  instance:
    hostname: 47.108.39.243
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
    fetch-registry: false
    register-with-eureka: false


