server:
  port: 5555

spring:
  application:
    name: xian-huiyuan
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/tuokebao
    username: root
    password: 123456


feign:
  client:
    config:
      zhongliang-yuangong:
        loggerLevel: FULL


eureka:
  client:
    service-url:
      defaultZone: http://localhost:9090/eureka
